general:
  enable_incomplete_verification: False
model:
  onnx_quirks: "{'Reshape': {'fix_batch_size': True}}"
solver:
  bound_prop_method: crown
bab:
  initial_max_domains: 10
  branching:
    input_split:
      enable: True
attack:
  pgd_order: before